services:
  db:
    image: postgres:15-alpine
    container_name: shop_final_db
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: shopdb
    ports: ["5432:5432"]
  backend:
    build: ./backend
    container_name: shop_final_back
    ports: ["8080:8080"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shopdb
      SPRING_DATASOURCE_USERNAME: usr
      SPRING_DATASOURCE_PASSWORD: pwd
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on: [db]
  frontend:
    build: ./frontend
    container_name: shop_final_front
    ports: ["5173:5173"]
    environment:
      VITE_API_URL: http://localhost:8080
    depends_on: [backend]
    # Volumen para que puedas editar si quieres
    volumes:
      - ./frontend/src:/app/src
